name: Flutter

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
          
      - name: verify runner
        run: |
          echo "Running on ${hostname}"
          echo $WKDIR
  
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/vagrant_private_key
          chmod 600 ~/.ssh/vagrant_private_key
          ssh-keyscan 192.168.56.4 >> ~/.ssh/known_hosts

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.0.2

      - name: create a working directory
        run: |
          echo "2"
          echo $(whoami)
          mkdir $(pwd)/my_flutter_app
          echo $(pwd)
          

      - name: Install dependencies
        # working-directory: $(pwd)/my_flutter_app
        run: |
           echo "3"
           flutter pub get
        
      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        # working-directory: $(pwd)/myflutter_app
        run: flutter test
