name: Flutter

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
          
      - name: verify runner
        run: |
          echo "Running on ${hostname}"
          echo "workspace: $GITHUB_WORKSPACE"
          echo $WKDIR
  
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/vagrant_private_key
          chmod 600 ~/.ssh/vagrant_private_key
          ssh-keyscan 192.168.56.4 >> ~/.ssh/known_hosts

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.0.2

      - name: create a working directory
        run: |
          # Copy all files to the working directory
          mkdir -p $GITHUB_WORKSPACE/my_flutter_app
          echo "present working directory is:"
          echo $GITHUB_WORKSPACE
          # cp -r $GITHUB_WORKSPACE/* $GITHUB_WORKSPACE/my_flutter_app/
          ls -la $GITHUB_WORKSPACE/my_flutter_app  # Verify pubspec.yaml exists
          

      - name: Install dependencies
        working-directory: $GITHUB_WORKSPACE/my_flutter_app
        run: |
           echo "Current directory: $(pwd)"
           flutter pub get
        
      - name: Analyze project source
        working-directory: $GITHUB_WORKSPACE/my_flutter_app
        run: dart analyze

      - name: Run tests
        working-directory: $GITHUB_WORKSPACE/my_flutter_app
        run: flutter test
